server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://avriznusvhfrpa:78eaf6293bc62a2f11e8c0710ea2d27924d46ee2ef12391bfe2a85e28f5756ee@ec2-34-232-191-133.compute-1.amazonaws.com:5432/d3ioo1p4m7gcj9
    username: avriznusvhfrpa
    password: 78eaf6293bc62a2f11e8c0710ea2d27924d46ee2ef12391bfe2a85e28f5756ee

jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true
  hibernate:
    ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0
